# Spring specific settings
spring:
  application:
    name: CGM - Assessment - REST
  main:
    show-banner: true

# server configuration
server:
  port: 8080
  contextPath:

# logging
logging:
  file: ./logs/app.log
  level.*: INFO
